[options]
admin_passwd = $pbkdf2-sha512$600000$RkgpZcwZg7B2TklJqdVaiw$FyzOsrubMNBaMuFmASpVVHQXN2vAf1B5LJSi88jXsOg/0vhjvrhsI1obXcgemrit7ks79VaJuZL3LZpxhIfilw
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
logfile = /var/log/odoo/odoo.log

